# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package qw_connection;
use base qw(Exporter);
use base qw(DynaLoader);
package qw_connectionc;
bootstrap qw_connection;
package qw_connection;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package qw_connection;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package qw_connection;

*QWC_Create = *qw_connectionc::QWC_Create;
*QWC_Connect = *qw_connectionc::QWC_Connect;
*QWC_Disconnect = *qw_connectionc::QWC_Disconnect;
*QWC_Say = *qw_connectionc::QWC_Say;
*QWC_SetSaveConsoleOutput = *qw_connectionc::QWC_SetSaveConsoleOutput;
*QWC_GetConsoleOutput = *qw_connectionc::QWC_GetConsoleOutput;
*QWC_Set_FPS = *qw_connectionc::QWC_Set_FPS;
*QWC_Quit = *qw_connectionc::QWC_Quit;
*QWC_GetQuit = *qw_connectionc::QWC_GetQuit;
*QWC_GetState = *qw_connectionc::QWC_GetState;

# ------- VARIABLE STUBS --------

package qw_connection;

*qwc_state_idle = *qw_connectionc::qwc_state_idle;
*qwc_state_connecting = *qw_connectionc::qwc_state_connecting;
*qwc_state_connected = *qw_connectionc::qwc_state_connected;
1;
